/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model.gltf --transform 
Files: model.gltf [105.07KB] > model-transformed.glb [782.23KB] (-644%)
Author: DogexorRexUwU (https://sketchfab.com/oscar.lopez.riviello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/falling-leaves-d552ce56772b4ad7815ac5957bd5e104
Title: Falling Leaves
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations, scene } = useGLTF(
    '/models/autumn-leaves/model.gltf'
  )

  // Here's the animation part
  let mixer = new THREE.AnimationMixer(scene)
  animations.forEach((clip) => {
    const action = mixer.clipAction(clip)
    action.timeScale = 0.3
    action.play()
  })

  useFrame((_, delta) => {
    mixer?.update(delta)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_30"
          geometry={nodes.Object_30.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_30.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_33"
          geometry={nodes.Object_33.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_33.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_36"
          geometry={nodes.Object_36.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_36.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_39"
          geometry={nodes.Object_39.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_39.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_42"
          geometry={nodes.Object_42.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_42.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_45.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_48"
          geometry={nodes.Object_48.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_48.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_51"
          geometry={nodes.Object_51.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_51.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_54"
          geometry={nodes.Object_54.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_54.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_57"
          geometry={nodes.Object_57.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_57.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_60"
          geometry={nodes.Object_60.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_60.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_63"
          geometry={nodes.Object_63.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_63.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_66"
          geometry={nodes.Object_66.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_66.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_69"
          geometry={nodes.Object_69.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_69.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_72"
          geometry={nodes.Object_72.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_72.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_75"
          geometry={nodes.Object_75.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_75.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_78"
          geometry={nodes.Object_78.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_78.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_81"
          geometry={nodes.Object_81.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_81.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_84"
          geometry={nodes.Object_84.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_84.skeleton}
          scale={0.01}
        />
        <skinnedMesh
          name="Object_87"
          geometry={nodes.Object_87.geometry}
          material={materials.material_0}
          skeleton={nodes.Object_87.skeleton}
          scale={0.01}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/autumn-leaves/model.gltf')
