import 'assets/styles/global.scss'
import './layout.scss'

import type { Metadata } from 'next'
import { Providers } from './providers'

import Image from 'next/image'
import localFont from 'next/font/local'

import Aside from '@/components/Aside'

// global fonts
const lato = localFont({
  src: [
    {
      path: '../assets/fonts/Lato/Lato-Bold.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Lato/Lato-Black.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
})

// global metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="ltr" className={lato.className + ' dark'}>
      <body>
        <Providers>
          <div className="root">
            <Aside />

            {children}
          </div>

          {/* background image */}
          <Image
            id="main-background-image"
            src={'/main-background.jpeg'}
            alt="Background image"
            fill
          />
        </Providers>
      </body>
    </html>
  )
}
