import 'assets/styles/global.scss'
import type { Metadata } from 'next'
import Image from 'next/image'
import localFont from 'next/font/local'

// global fonts
const lato = localFont({
  src: [
    {
      path: '../assets/fonts/Lato/Lato-Bold.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Lato/Lato-Black.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        {children}

        <Image
          id="main-background-image"
          src={'/main-background.jpeg'}
          alt="Picture of the author"
          fill
        />
      </body>
    </html>
  )
}
